### ISSUE TITLE
BORDL: Seg fault when loading module in 2.0.16

### ISSUE THREAD

**Issue by cschol** [sebastien-bouffier/Bidoo#204]
OS (if applicable): GNU/Linux
Version (or "dev" if compiling from source): 2.0.16

Backtrace:

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f68a656579f in unlink_chunk (p=p@entry=0x55c94898ec50, av=0x7f68a66ddc80 <main_arena>) at ./malloc/malloc.c:1628
1628    ./malloc/malloc.c: No such file or directory.
[Current thread is 1 (Thread 0x7f68a54ca800 (LWP 3334775))]
(gdb) bt
#0  0x00007f68a656579f in unlink_chunk (p=p@entry=0x55c94898ec50, av=0x7f68a66ddc80 <main_arena>) at ./malloc/malloc.c:1628
#1  0x00007f68a65686ab in _int_malloc (av=av@entry=0x7f68a66ddc80 <main_arena>, bytes=bytes@entry=184) at ./malloc/malloc.c:4307
#2  0x00007f68a65691b9 in __GI___libc_malloc (bytes=184) at ./malloc/malloc.c:3329
#3  0x00007f68a6a139c4 in nsvg__addShape (p=p@entry=0x55c9488108b0) at dep/include/nanosvg.h:948
#4  0x00007f68a6a177b8 in nsvg__parseRect (attr=<optimized out>, p=<optimized out>) at dep/include/nanosvg.h:2366
#5  nsvg__startElement (attr=<optimized out>, el=0x7a <error: Cannot access memory at address 0x7a>, ud=0x55c9488108b0) at dep/include/nanosvg.h:2690
#6  nsvg__startElement (ud=ud@entry=0x55c9488108b0, el=el@entry=0x55c94626d670 "path", attr=attr@entry=0x7ffc22800d80) at dep/include/nanosvg.h:2663
#7  0x00007f68a6a0ec35 in nsvg__parseElement (s=<optimized out>, s@entry=0x55c94626d670 "path", startelCb=startelCb@entry=0x7f68a6a16b30 <nsvg__startElement(void*, char const*, char const**)>, endelCb=endelCb@entry=0x7f68a6a0fa10 <nsvg__endElement(void*, char const*)>, ud=ud@entry=0x55c9488108b0)
    at dep/include/nanosvg.h:326
#8  0x00007f68a6a1ab5e in nsvg__parseXML (input=input@entry=0x55c94625e270 "", startelCb=startelCb@entry=0x7f68a6a16b30 <nsvg__startElement(void*, char const*, char const**)>, endelCb=endelCb@entry=0x7f68a6a0fa10 <nsvg__endElement(void*, char const*)>, 
    contentCb=contentCb@entry=0x7f68a6a0e600 <nsvg__content(void*, char const*)>, ud=ud@entry=0x55c9488108b0) at dep/include/nanosvg.h:350
#9  0x00007f68a6a1ae9e in nsvgParse (input=input@entry=0x55c94625e270 "", units=units@entry=0x7f68a6fbbb9b "px", dpi=dpi@entry=75) at dep/include/nanosvg.h:2887
#10 0x00007f68a6a1b7b6 in nsvgParseFromFile (filename=<optimized out>, units=0x7f68a6fbbb9b "px", dpi=75) at dep/include/nanosvg.h:2917
#11 0x00007f68a6b01fcb in rack::window::Svg::loadFile (this=this@entry=0x55c94526e2a0, filename="/home/cschol/src/Rack-2.0/plugins/Bidoo/res/BORDL.svg") at /usr/include/c++/11/bits/basic_string.h:194
#12 0x00007f68a4f9eeb2 in BidooWidget::prepareThemes (this=0x55c948810470, filename="/home/cschol/src/Rack-2.0/plugins/Bidoo/res/BORDL.svg") at src/plugin.cpp:196
#13 0x00007f68a4f01034 in BORDLWidget::BORDLWidget (this=0x55c948810470, module=0x55c9489685f0) at src/BORDL.cpp:1158
```

The issue is introduced with this commit: `241ca4b5e33d33cb38cda81088d465f964b57a0a` (v2.0.152).
v2.0.15 and below seem to work correctly.

Now, the code change is unrelated, but maybe the quantizer initialization overruns memory?

**Comment by sebastien-bouffier** [comment]
Hi @cschol yes it is possible I will look at it asap. Thanks for the back trace.

**Comment by sebastien-bouffier** [comment]
Can you test if my last push fix the issue with BORDL please ?
Best.

**Comment by sebastien-bouffier** [comment]
VMware installed, Ubuntu installed, bordL seems to run fine I push a new release and update the request under VCV library 
Best.

**Comment by cschol** [comment]
Hey, this does indeed fix the crash on my system. Thank you!
